spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related QA APIs"
  contactDetails:
    name: "Chil Hoan- Developer"
    email: "chilhoank@yahoo.ca"
  onCallSupport:
    - (647) 571-9437
    - (905) 765-9437